"""Step 5: results/REPORT.md -- leaderboard score vs contamination-corrected score. No GPU, seconds.

  uv run python scripts/a5_report.py

FinBen's metrics (PIXIU flare.py): accuracy, weighted F1 (their headline "F1"), macro F1, MCC, missing.
Test subsets:  full (= leaderboard) | clean (no near-copy in train/valid) | contaminated (the rest)

Two independent estimates of how much contamination inflates the leaderboard number:
  (a) filter the TEST set:   inflation = [F1(full) - F1(clean)] of QLoRA  minus  the same for zero-shot.
      Zero-shot trained on none of these sentences, so its difference is pure difficulty (the clean and
      contaminated subsets needn't be equally hard); subtracting it isolates memorisation.
  (b) clean the TRAINING set: QLoRA trained on train vs QLoRA trained on train minus near-copies, both
      scored on the contaminated test sentences. Same model, same seeds; the only difference is whether it
      saw those near-copies. On the clean subset the two should tie (a built-in control).
If (a) and (b) roughly agree, the contamination estimate is trustworthy.
"""
import json
import re
from collections import defaultdict

import numpy as np
import pandas as pd
from scipy.stats import binomtest
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef

import config_a as config  # noqa: F401
from config_a import DATA_DIR, LABELS, PRED_DIR, RESULTS_DIR, TASK_DIR
from ftlib.metrics import expected_calibration_error

cont = pd.read_csv(DATA_DIR / "contamination.csv")
preds = {f.stem: pd.read_csv(f, keep_default_na=False) for f in sorted(PRED_DIR.glob("*.csv"))}
partial = sorted(k for k, v in preds.items() if len(v) != len(cont))
preds = {k: v for k, v in preds.items() if len(v) == len(cont)}
if not preds:
    raise SystemExit("no complete prediction files yet -- run 04_eval.py")
subsets = {"full": np.ones(len(cont), bool), "clean": ~cont.contaminated.values, "contaminated": cont.contaminated.values}


def wf1(g, p):
    return f1_score(g, p, average="weighted", zero_division=0)


def metrics(d, m):
    g, p = d.gold.values[m], d.pred.values[m]
    return {"acc": accuracy_score(g, p), "wf1": wf1(g, p), "mf1": f1_score(g, p, labels=LABELS, average="macro", zero_division=0),
            "mcc": matthews_corrcoef(g, p), "missing": float(np.mean(p == "missing"))}


def boot_ci(d, m, n=1000):
    g, p = d.gold.values[m], d.pred.values[m]
    rng = np.random.default_rng(0)
    v = [wf1(g[i], p[i]) for i in (rng.integers(0, len(g), len(g)) for _ in range(n))]
    return np.quantile(v, 0.025), np.quantile(v, 0.975)


def mcnemar(a_df, b_df, m):
    a, b = a_df.pred.values[m] == a_df.gold.values[m], b_df.pred.values[m] == b_df.gold.values[m]
    x, y = int(np.sum(a & ~b)), int(np.sum(~a & b))
    return (binomtest(x, x + y, 0.5).pvalue if x + y else 1.0), x, y


def variant(name):
    m = re.match(r"qlora_seed(\d+)(-decontam)?$", name)
    if m:
        return "QLoRA, decontaminated train" if m[2] else "QLoRA, FinBen train"
    return {"e4b_zeroshot": "E4B-it zero-shot", "finbert": "FinBERT †"}.get(name, name)


groups = defaultdict(list)
for name in preds:
    groups[variant(name)].append(name)
ORDER = ["E4B-it zero-shot", "QLoRA, FinBen train", "QLoRA, decontaminated train", "FinBERT †"]
gorder = sorted(groups, key=lambda g: ORDER.index(g) if g in ORDER else 99)
M = {g: {s: [metrics(preds[n], m) for n in groups[g]] for s, m in subsets.items()} for g in groups}


def agg(g, s, k):
    v = [x[k] for x in M[g][s]]
    return np.mean(v), (np.std(v, ddof=1) if len(v) > 1 else None)


def show(g, s, k, pct=False):
    mu, sd = agg(g, s, k)
    f = (lambda x: f"{x:.1%}") if pct else (lambda x: f"{x:.3f}")
    return f(mu) + (f" ± {sd:.3f}" if sd is not None else "")


n = len(cont)
lines = ["# Part A: contamination (generated by `a5_report.py`)", ""]

# 1. contamination
c = cont[cont.contaminated]
lines += ["## 1. How much of FinBen's FPB test set is in its own training split?", "",
          "| Detector | Test sentences | Share |", "|---|---|---|"]
for det, label in [("exact", "exact (normalised text)"), ("near_dup", f"near-duplicate (cosine ≥ {config.NEAR_DUP_THRESHOLD})"),
                   ("contaminated", "**contaminated = exact or near-duplicate**"),
                   ("ngram", f"shares a word {config.NGRAM_N}-gram (loose; over-fires on boilerplate)"),
                   ("loose", "loose = any of the three (sensitivity check)")]:
    lines.append(f"| {label} | {int(cont[det].sum())} | {cont[det].mean():.1%} |")
lines += ["", f"**Clean subset: {int((~cont.contaminated).sum())} of {n}** ({(~cont.contaminated).mean():.1%})."]
if len(c):
    lines.append(f"Contaminated sentences whose training copy has the same label: **{c.same_label_as_seen.mean():.1%}** "
                 f"({int((~c.same_label_as_seen).sum())} carry a DIFFERENT label in train: memorising those costs points).")
if "in_validation" in cont:
    lines.append(f"Test sentences with a near-copy in the validation split (watched, never trained on): {int(cont.in_validation.sum())}.")
dec = DATA_DIR / "finben_train_decontam.csv"
if dec.exists():
    lines.append(f"Decontaminated training set: {len(pd.read_csv(dec))} of {len(pd.read_csv(DATA_DIR / 'finben_train.csv'))} train sentences kept.")
if "agreement" in cont:
    lines += ["", "| PhraseBank agreement level | Test sentences | Contaminated |", "|---|---|---|"]
    for lv, grp in cont.groupby("agreement"):
        lines.append(f"| {lv} | {len(grp)} | {grp.contaminated.mean():.1%} |")
lines.append("")

# 2. scores
lines += ["## 2. Scores: leaderboard (full) vs clean vs contaminated", "",
          "Weighted F1 is FinBen's headline metric. QLoRA rows: mean ± std over seeds.", "",
          f"| System | Full (n={n}): acc / **wF1** / macro-F1 / MCC / missing | Clean wF1 (n={int(subsets['clean'].sum())}) | "
          f"Contaminated wF1 (n={int(subsets['contaminated'].sum())}) | ECE (full) |",
          "|---|---|---|---|---|"]
for g in gorder:
    full = " / ".join(show(g, "full", k) if k == "wf1" else f"{agg(g, 'full', k)[0]:.3f}" for k in ["acc", "wf1", "mf1", "mcc"])
    full = full.replace(show(g, "full", "wf1"), f"**{show(g, 'full', 'wf1')}**", 1) + f" / {agg(g, 'full', 'missing')[0]:.1%}"
    clean = show(g, "clean", "wf1")
    if len(groups[g]) == 1:
        lo, hi = boot_ci(preds[groups[g][0]], subsets["clean"])
        clean += f" [{lo:.3f}, {hi:.3f}]"
    eces = [expected_calibration_error(preds[x].gold, preds[x][[f"p_{l}" for l in LABELS]].values, LABELS)[0] for x in groups[g]]
    lines.append(f"| {g}{f' (n={len(groups[g])})' if len(groups[g]) > 1 else ''} | {full} | {clean} | "
                 f"{show(g, 'contaminated', 'wf1')} | {np.mean(eces):.3f} |")
if subsets["contaminated"].sum() < 30:
    lines += ["", f"*Only {int(subsets['contaminated'].sum())} contaminated sentences: scores on that subset are too noisy to interpret.*"]
lines += ["", "† FinBERT was fine-tuned on Financial PhraseBank itself, so every FPB test sentence may be in its training "
              "data; none of its scores is a clean measurement.", ""]
if partial:
    lines += [f"*Partial runs (smoke tests), not shown: {', '.join(partial)}.*", ""]

# 3. the two contamination estimates
zs, ql, dc = "E4B-it zero-shot", "QLoRA, FinBen train", "QLoRA, decontaminated train"
est = []
if zs in M and ql in M:
    d_ql = np.mean([f["wf1"] - cl["wf1"] for f, cl in zip(M[ql]["full"], M[ql]["clean"])])
    d_zs = agg(zs, "full", "wf1")[0] - agg(zs, "clean", "wf1")[0]
    est.append(f"| (a) filter the test set | QLoRA full − clean = {d_ql:+.3f}; zero-shot full − clean = {d_zs:+.3f} | **{d_ql - d_zs:+.3f}** |")
if ql in M and dc in M:
    on_cont = agg(ql, "contaminated", "wf1")[0] - agg(dc, "contaminated", "wf1")[0]
    on_clean = agg(ql, "clean", "wf1")[0] - agg(dc, "clean", "wf1")[0]
    share = subsets["contaminated"].mean()
    est.append(f"| (b) clean the training set | trained-on-copies − decontaminated: contaminated subset {on_cont:+.3f}, "
               f"clean subset {on_clean:+.3f} (control, should be ≈ 0) | **{on_cont * share:+.3f}** (= {on_cont:+.3f} × {share:.0%} of test) |")
if est:
    lines += ["## 3. How much does contamination inflate the leaderboard number?", "",
              "| Method | Ingredients (weighted F1) | Estimated inflation of full-test wF1 |", "|---|---|---|", *est, "",
              "*If (a) and (b) agree, the estimate is trustworthy. If (b)'s clean-subset control is far from 0, the two "
              "training sets differ in more than the copies (e.g. size), and (b) is confounded.*", ""]

# 4. significance
sig = []
for name in sorted(preds):
    if name.startswith("qlora_seed") and "e4b_zeroshot" in preds:
        p, x, y = mcnemar(preds[name], preds["e4b_zeroshot"], subsets["clean"])
        sig.append(f"| {name} vs zero-shot | clean | +{x} / −{y} | {p:.2g} |")
    m = re.match(r"(qlora_seed\d+)-decontam$", name)
    if m and m[1] in preds:
        p, x, y = mcnemar(preds[m[1]], preds[name], subsets["contaminated"])
        sig.append(f"| {m[1]} vs {name} | contaminated | +{x} / −{y} | {p:.2g} |")
if sig:
    lines += ["## 4. Significance (McNemar, same sentences)", "",
              "| Comparison | Subset | Only first right / only second right | p |", "|---|---|---|---|", *sig, ""]

# 5. format
fmt_rows = [f"| {name} | {d.strict_format.astype(str).str.lower().eq('true').mean():.1%} | {np.mean(d.pred.values == 'missing'):.1%} |"
            for name, d in preds.items() if "strict_format" in d]
if fmt_rows:
    lines += ["## 5. Answer format", "", "| System | Reply is exactly one label | FinBen 'missing' |", "|---|---|---|", *fmt_rows, ""]

# 6. training cost
infos = [json.loads(f.read_text()) for f in sorted(config.ADAPTERS_DIR.glob("fpb-seed*/train_info.json"))]   # Part A runs only
if infos:
    lines += ["## 6. Training runs", "", "| Run | Train examples | Minutes | Val loss | Peak VRAM (GB) |", "|---|---|---|---|---|"]
    lines += [f"| {i['run']} | {i['train_examples']} | {i['seconds'] / 60:.1f} | {i['val_loss'] if i['val_loss'] is None else round(i['val_loss'], 3)} | {i['peak_vram_gb']} |" for i in infos]
    lines.append("")

(RESULTS_DIR / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")
print("\n".join(lines))
