"""Part B report: results/partB/REPORT.md. No GPU, seconds.

  uv run python scripts/b5_report.py

Verdict rule (fixed before any test result existed):
  "beats FinMA"            our final model's test wF1 > FinMA's (our re-run, same prompt/parser/metric)
                           AND McNemar p < 0.05 on the same test sentences
  "ahead, not significant" higher wF1 but p >= 0.05
  "behind"                 lower wF1
The published FinMA number (0.88, FinBen paper) is shown for reference; the like-for-like comparison is
our own re-run.
"""
import json
import re

import numpy as np
import pandas as pd
from scipy.stats import binomtest
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef

import config_b as config
import b3_select as selection
import preds
from config_b import LABELS

P = config.PRED_DIR


def read(split, name):
    f = P / split / f"{name}.csv"
    return preds.read(f)   # None if missing; gold joined from data/ by id


def m(gold, pred):
    return {"acc": accuracy_score(gold, pred), "wf1": f1_score(gold, pred, average="weighted", zero_division=0),
            "mf1": f1_score(gold, pred, labels=LABELS, average="macro", zero_division=0), "mcc": matthews_corrcoef(gold, pred)}


def boot(gold, pred, n=1000):
    g, p = np.asarray(gold), np.asarray(pred)
    rng = np.random.default_rng(0)
    v = [f1_score(g[i], p[i], average="weighted", zero_division=0) for i in (rng.integers(0, len(g), len(g)) for _ in range(n))]
    return np.quantile(v, 0.025), np.quantile(v, 0.975)


def mcnemar(gold, a, b):
    a, b = np.asarray(a) == np.asarray(gold), np.asarray(b) == np.asarray(gold)
    x, y = int(np.sum(a & ~b)), int(np.sum(~a & b))
    return (binomtest(x, x + y, 0.5).pvalue if x + y else 1.0), x, y


lines = ["# Part B: beating FinMA-7B (generated by `b5_report.py`)", ""]

# ---- 1. search on validation
t = selection.score_table()
if not t.empty:
    t = t.sort_values(["epochs", "lr", "rank"])
    lines += ["## 1. Search on VALIDATION (776 sentences; the test set was not used)", "",
              "| Epochs | LR | Rank | Seeds | wF1 generated | ± std | wF1 argmax | wF1 3-seed ensemble |", "|---|---|---|---|---|---|---|---|"]
    for _, r in t.iterrows():
        f = lambda v: "—" if pd.isna(v) else f"{v:.4f}"
        lines.append(f"| {r.epochs} | {r.lr:g} | {r['rank']} | {r.seeds} | **{r.wf1_generated:.4f}** | {f(r['std'])} | {f(r.wf1_argmax)} | {f(r.wf1_ensemble)} |")
    zs = read("validation", "e4b_zeroshot")
    if zs is not None:
        lines.append(f"| zero-shot | — | — | — | {m(zs.gold, zs.pred)['wf1']:.4f} | | | |")
    curves = []
    for f in sorted(config.ADAPTERS_DIR.glob(f"e*_s{config.SEARCH_SEED}/train_info.json")):
        i = json.loads(f.read_text())
        if i.get("val_loss_curve"):
            curves.append(f"| {i['run']} | " + " → ".join(f"{l:.3f}" for _, l in i["val_loss_curve"]) + " |")
    if curves:
        lines += ["", "Validation loss during training (logged twice per epoch):", "", "| Run | Validation loss |", "|---|---|", *curves]
    lines.append("")
sel = json.loads(config.SELECTED.read_text()) if config.SELECTED.exists() else None
if sel:
    lines += [f"**Frozen choice:** {sel['epochs']} epoch(s), learning rate {sel['lr']:g}, rank {sel['rank']}, "
              f"decoding = {sel['decoding']}, seed ensemble = {'yes' if sel['ensemble'] else 'no'}. Rule: {sel['rule']}.", ""]

# ---- 2. final test results
test = pd.read_csv(config.DATA_DIR / config.SPLIT_FILES["test"])
gold = test.answer.str.strip().str.lower().values
finals = {int(re.search(r"_s(\d+)_tv$", f.stem)[1]): pd.read_csv(f, keep_default_na=False)
          for f in (P / "test").glob("e*_tv.csv")} if (P / "test").exists() else {}
col = "pred_argmax" if sel and sel["decoding"] == "argmax" else "pred"
systems = {}
if finals:
    for s, d in sorted(finals.items()):
        systems[f"Ours, seed {s}"] = d[col].values
    if len(finals) > 1:
        probs = np.mean([d[[f"p_{l}" for l in LABELS]].values for d in finals.values()], axis=0)
        systems["Ours, 3-seed ensemble"] = np.array(LABELS)[probs.argmax(1)]
for label, name in [("E4B-it zero-shot", "e4b_zeroshot"), ("FinMA-7B (our re-run)", "finma_7b"),
                    ("FinMA-7B, raw prompt (sensitivity)", "finma_7b_rawprompt")]:
    d = read("test", name)
    if d is not None:
        systems[label] = d.pred.values
cont = pd.read_csv(config.DATA_DIR / "contamination.csv") if (config.DATA_DIR / "contamination.csv").exists() else None
clean = None
if cont is not None:
    seen = cont.contaminated | cont.get("in_validation", False)     # final model also trained on validation
    clean = ~seen.values

if systems:
    lines += ["## 2. TEST results (970 sentences, scored once)", "",
              "| System | wF1 [95% CI] | Accuracy | Macro-F1 | MCC | Clean-subset wF1 |", "|---|---|---|---|---|---|"]
    for label, pred in systems.items():
        r = m(gold, pred)
        lo, hi = boot(gold, pred)
        cw = f"{m(gold[clean], pred[clean])['wf1']:.4f} (n={clean.sum()})" if clean is not None else "—"
        lines.append(f"| {label} | **{r['wf1']:.4f}** [{lo:.3f}, {hi:.3f}] | {r['acc']:.4f} | {r['mf1']:.4f} | {r['mcc']:.4f} | {cw} |")
    seeds_w = [m(gold, systems[k])["wf1"] for k in systems if k.startswith("Ours, seed")]
    if len(seeds_w) > 1:
        lines.append(f"| **Ours, mean ± std over seeds** | **{np.mean(seeds_w):.4f} ± {np.std(seeds_w, ddof=1):.4f}** | | | | |")
    lines += [f"| FinMA-7B (published, FinBen paper) | {config.FINMA_PUBLISHED_F1:.2f} | | | | |", "",
              "*FinMA (our re-run) uses its official prompt wrapper (`Human:` + query + `Assistant:`, `finma_prompt` in PIXIU's "
              "`model_prompt.py`); the raw-prompt row shows how much that wrapper matters. The verdict uses the official one.*", "",
              "*Clean subset = test sentences with no near-copy in train or validation (the final model trained on both).*", ""]

# ---- 3. head to head
finma = systems.get("FinMA-7B (our re-run)")
verdict = None
if finma is not None and finals:
    rows = []
    for label, pred in systems.items():
        if label.startswith("Ours"):
            for subset, mask in [("full", np.ones(len(gold), bool))] + ([("clean", clean)] if clean is not None else []):
                p, x, y = mcnemar(gold[mask], pred[mask], finma[mask])
                d_w = m(gold[mask], pred[mask])["wf1"] - m(gold[mask], finma[mask])["wf1"]
                rows.append(f"| {label} | {subset} | {d_w:+.4f} | +{x} / −{y} | {p:.2g} |")
    lines += ["## 3. Head to head with FinMA-7B on the same sentences", "",
              "| Our system | Subset | wF1 difference (ours − FinMA) | Only ours right / only FinMA right | McNemar p |",
              "|---|---|---|---|---|", *rows, ""]
    main = systems.get("Ours, 3-seed ensemble") if sel and sel["ensemble"] else None
    main_label = "3-seed ensemble" if main is not None else "each seed"
    preds_main = [main] if main is not None else [systems[k] for k in systems if k.startswith("Ours, seed")]
    outcomes = []
    for pr in preds_main:
        p, _, _ = mcnemar(gold, pr, finma)
        dw = m(gold, pr)["wf1"] - m(gold, finma)["wf1"]
        outcomes.append("beats FinMA" if dw > 0 and p < 0.05 else "ahead, not significant" if dw > 0 else "behind")
    verdict = f"{main_label}: " + ", ".join(outcomes)

# ---- 4. memorisation check
mem = []
for label, name in [("E4B-it zero-shot (trained on nothing)", "e4b_zeroshot"), ("FinMA-7B", "finma_7b")] + \
        ([(f"Ours, train-only twin (seed {config.SEARCH_SEED})",
           f"e{sel['epochs']}_lr{sel['lr']:g}_r{sel['rank']}_s{config.SEARCH_SEED}")] if sel else []):
    tr, te = read("train_sample", name), read("test", name)
    if tr is not None and te is not None:
        a_tr, a_te = accuracy_score(tr.gold, tr.pred), accuracy_score(te.gold, te.pred)
        mem.append((label, a_tr, a_te))
if mem:
    lines += ["## 4. Memorisation check: accuracy on training sentences vs test sentences", "",
              f"A model that trained on a sentence does better on it. Zero-shot trained on nothing, so its gap is the "
              f"difficulty difference between the two sets ({config.MEMO_SAMPLE} random train sentences vs the 970 test sentences).", "",
              "| Model | Train-sample accuracy | Test accuracy | Gap (train − test) |", "|---|---|---|---|"]
    lines += [f"| {l} | {a:.4f} | {b:.4f} | {a - b:+.4f} |" for l, a, b in mem]
    lines += ["", "*A fine-tuned model trained on train only should show a clear positive gap. A gap near zero for a fine-tuned "
                  "model means it either memorised little, or also trained on the test sentences. Compare with our train-only twin.*", ""]

# ---- 4b. sharper contamination diagnostics for FinMA
fin_te, fin_tr = read("test", "finma_7b"), read("train_sample", "finma_7b")
twin_name = f"e{sel['epochs']}_lr{sel['lr']:g}_r{sel['rank']}_s{config.SEARCH_SEED}" if sel else None
twin_te, twin_tr = (read("test", twin_name), read("train_sample", twin_name)) if twin_name else (None, None)
zs_te, zs_tr = read("test", "e4b_zeroshot"), read("train_sample", "e4b_zeroshot")
if all(x is not None for x in [fin_te, fin_tr, twin_te, twin_tr, zs_te, zs_tr]) and "agreement" in test:
    trs = pd.read_csv(config.DATA_DIR / config.SPLIT_FILES["train"]).sample(config.MEMO_SAMPLE, random_state=0).reset_index(drop=True)
    order = ["AllAgree", "75Agree", "66Agree", "50Agree"]
    acc_by = lambda d, df: [np.mean(d.pred.values[df.agreement.values == lv] == d.gold.values[df.agreement.values == lv]) for lv in order]
    rows = [("E4B-it zero-shot, test (never trained)", zs_te, test), ("Ours, train-only twin, **test (unseen)**", twin_te, test),
            ("Ours, train-only twin, **train (seen)**", twin_tr, trs), ("**FinMA-7B, test**", fin_te, test), ("FinMA-7B, train", fin_tr, trs)]
    lines += ["## 4b. Did FinMA see the test sentences? Accuracy by annotator agreement", "",
              "PhraseBank records how many annotators agreed. On **50Agree** sentences the humans split, so a model that has "
              "not seen the gold label can't do much better than the label's own ambiguity allows. A model that memorised "
              "the label can.", "",
              "| Model, split | AllAgree | 75Agree | 66Agree | **50Agree** |", "|---|---|---|---|---|"]
    lines += [f"| {lbl} | " + " | ".join(f"{a:.3f}" for a in acc_by(d, df)) + " |" for lbl, d, df in rows]
    zs_wrong_te, zs_wrong_tr = zs_te.pred.values != zs_te.gold.values, zs_tr.pred.values != zs_tr.gold.values
    hit = lambda d, msk: np.mean(d.pred.values[msk] == d.gold.values[msk])
    lines += ["", f"On the sentences zero-shot gets wrong (the hard ones): our twin scores **{hit(twin_te, zs_wrong_te):.3f}** on unseen test "
                  f"sentences (n={zs_wrong_te.sum()}) and **{hit(twin_tr, zs_wrong_tr):.3f}** on train sentences it trained on "
                  f"(n={zs_wrong_tr.sum()}); FinMA scores **{hit(fin_te, zs_wrong_te):.3f} on the test ones**.", ""]
    if cont is not None:
        conf = (cont.contaminated & ~cont.same_label_as_seen).values
        if conf.any():
            tl = lambda d: int(np.sum(d.pred.values[conf] == cont.gold.values[conf]))
            cl = lambda d: int(np.sum(d.pred.values[conf] == cont.nearest_seen_label.values[conf]))
            lines += [f"The {conf.sum()} test sentences whose train near-copy carries a DIFFERENT label: our twin follows the test label "
                      f"{tl(twin_te)}/{conf.sum()} (train label {cl(twin_te)}); FinMA follows the test label {tl(fin_te)}/{conf.sum()} "
                      f"(train label {cl(fin_te)}). Too few to decide anything.", ""]

par = config.RESULTS_DIR / "harness_parity.json"
if par.exists():
    pj = json.loads(par.read_text())
    lines += ["## 5. Parity with FinBen's official scoring code", "",
              f"Re-scoring every saved test output with PIXIU's `flare.py` code (copied verbatim, `b4_harness_parity.py`): "
              f"**{'identical predictions and metrics' if pj['identical_to_pixiu_scoring'] else 'MISMATCH, investigate'}** "
              f"for {len(pj['systems'])} systems. The remaining difference from the official harness is only how the "
              "model is loaded (4-bit with the per-layer table in CPU RAM), not how it's prompted, decoded or scored.", ""]
if verdict:
    lines += ["## Verdict (rule fixed before the test run)", "", f"**{verdict}**", ""]
(config.RESULTS_DIR / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")
print("\n".join(lines))
