"""Part C, step 4: results/partC/REPORT.md -- does FinMA's lead survive on sentences it can't have seen?

  uv run python scripts/c4_report.py

Gold labels = data/fresh/labels.csv (adjudicated 'final' if set, else the blind 'human' label); excluded
sentences are dropped. AS SHIPPED that file was labelled by an AI (Claude), not a human: the report says so
and asks for a human spot-check (c2_label.py --spotcheck 40). With human labels, scores against the second
annotator are shown as a sensitivity check.

DECISION RULE (fixed 2026-10-01, before any fresh-set result existed):
  lead(X) = FinMA wF1 - our 3-seed-ensemble wF1 on test set X
  shrink  = lead(FinBen test) - lead(fresh)
  "memorisation consistent"     shrink >= 0.03 AND the 95% bootstrap CI of shrink excludes 0
  "memorisation not supported"  FinMA still leads by >= 0.03 on fresh AND McNemar p < 0.05
  "inconclusive"                anything else
"""
import json

import numpy as np
import pandas as pd
from scipy.stats import binomtest
from sklearn.metrics import accuracy_score, cohen_kappa_score, f1_score

import config_b as config
from config_b import LABELS

C_DIR = config.ROOT / "results" / "partC"
FRESH = config.DATA_DIR / "fresh"
MIN_SHRINK = 0.03


def wf1(g, p):
    return f1_score(g, p, average="weighted", zero_division=0)


def boot(g, p, n=2000, seed=0):
    g, p = np.asarray(g), np.asarray(p)
    rng = np.random.default_rng(seed)
    v = [wf1(g[i], p[i]) for i in (rng.integers(0, len(g), len(g)) for _ in range(n))]
    return np.quantile(v, 0.025), np.quantile(v, 0.975)


def mcnemar(g, a, b):
    a, b = np.asarray(a) == np.asarray(g), np.asarray(b) == np.asarray(g)
    x, y = int(np.sum(a & ~b)), int(np.sum(~a & b))
    return (binomtest(x, x + y, 0.5).pvalue if x + y else 1.0), x, y


def ensemble(dfs):
    return np.array(LABELS)[np.mean([d[[f"p_{l}" for l in LABELS]].values for d in dfs], axis=0).argmax(1)]


sel = json.loads(config.SELECTED.read_text())
final = [f"e{sel['epochs']}_lr{sel['lr']:g}_r{sel['rank']}_s{s}_tv" for s in config.SEEDS]
cand = pd.read_csv(FRESH / "candidates.csv")
lab = pd.read_csv(FRESH / "labels.csv", keep_default_na=False, dtype=str) if (FRESH / "labels.csv").exists() else None
lines = ["# Part C: a fresh test set FinMA can't have seen (generated by `c4_report.py`)", ""]
n_lab = 0 if lab is None else int(lab.human.ne("").sum())
ai_gold = lab is not None and "labeled_by" in lab and lab.labeled_by.str.contains("claude", case=False).any()
lines += [f"{len(cand)} sentences from Nordic company press releases dated {pd.read_csv(FRESH / 'candidates.csv').date.min()} "
          f"to {cand.date.max()} ({(cand.get('selection', 'random') == 'random').sum()} random, "
          f"{(cand.get('selection', '') == 'negative-keyword enrichment').sum()} added by negative-keyword enrichment). "
          f"Labelled: **{n_lab}/{len(cand)}**" + (" **by Claude (AI), at the user's request -- not human gold labels**" if ai_gold else " by you") + ".", ""]
if ai_gold:
    lines += ["> **Caveat:** the answer key was made by an LLM, and the systems being compared are LLMs. An LLM's reading of "
              "sentiment could favour some models over others. See section 4 for how well a human agrees with it.", ""]

preds = {}
for name in ["e4b_zeroshot", "finma_7b", *final]:
    f = C_DIR / "predictions" / f"{name}.csv"
    if f.exists():
        preds[name] = pd.read_csv(f, keep_default_na=False)
have_ours = all(n in preds for n in final)

if lab is None or n_lab == 0 or "finma_7b" not in preds or not have_ours:
    missing = ([] if n_lab else ["labels (`c2_label.py`)"]) + ([] if "finma_7b" in preds and have_ours else
                                                               ["model predictions (`run_all.py` runs `c3_eval.py`)"])
    lines += [f"*Not ready: waiting for {' and '.join(missing)}.*"]
else:
    gold = lab.final.where(lab.final != "", lab.human).values
    keep = np.isin(gold, LABELS)
    g = gold[keep]
    systems = {"E4B-it zero-shot": preds["e4b_zeroshot"].pred.values[keep] if "e4b_zeroshot" in preds else None,
               **{f"Ours, seed {s}": preds[n].pred.values[keep] for s, n in zip(config.SEEDS, final)},
               "Ours, 3-seed ensemble": ensemble([preds[n] for n in final])[keep],
               "FinMA-7B (official prompt)": preds["finma_7b"].pred.values[keep]}
    systems = {k: v for k, v in systems.items() if v is not None}

    # FinBen test scores of the same systems (Part B, scored once)
    ft = pd.read_csv(config.DATA_DIR / config.SPLIT_FILES["test"])
    fg = ft.answer.str.strip().str.lower().values
    rd = lambda n: pd.read_csv(config.PRED_DIR / "test" / f"{n}.csv", keep_default_na=False)
    fin_sys = {"E4B-it zero-shot": rd("e4b_zeroshot").pred.values,
               **{f"Ours, seed {s}": rd(n).pred.values for s, n in zip(config.SEEDS, final)},
               "Ours, 3-seed ensemble": ensemble([rd(n) for n in final]),
               "FinMA-7B (official prompt)": rd("finma_7b").pred.values}

    counts = pd.Series(g).value_counts().reindex(LABELS, fill_value=0)
    lines += [f"Gold labels used: {keep.sum()} sentences (negative {counts['negative']}, neutral {counts['neutral']}, "
              f"positive {counts['positive']}); {(~keep).sum()} excluded or unlabelled.", "",
              "## 1. Scores: FinBen test (970) vs fresh 2026 sentences", "",
              "| System | FinBen test wF1 | Fresh wF1 [95% CI] | Fresh accuracy | Fresh macro-F1 | Drop (fresh − FinBen) |",
              "|---|---|---|---|---|---|"]
    for k, p in systems.items():
        lo, hi = boot(g, p)
        fw = wf1(fg, fin_sys[k])
        lines.append(f"| {k} | {fw:.4f} | **{wf1(g, p):.4f}** [{lo:.3f}, {hi:.3f}] | {accuracy_score(g, p):.4f} | "
                     f"{f1_score(g, p, labels=LABELS, average='macro', zero_division=0):.4f} | {wf1(g, p) - fw:+.4f} |")

    # the decision
    ours, finma = systems["Ours, 3-seed ensemble"], systems["FinMA-7B (official prompt)"]
    lead_fin = wf1(fg, fin_sys["FinMA-7B (official prompt)"]) - wf1(fg, fin_sys["Ours, 3-seed ensemble"])
    lead_fresh = wf1(g, finma) - wf1(g, ours)
    shrink = lead_fin - lead_fresh
    rng = np.random.default_rng(0)
    sh = []
    for _ in range(2000):   # the two test sets are independent: resample each on its own
        i, j = rng.integers(0, len(fg), len(fg)), rng.integers(0, len(g), len(g))
        sh.append((wf1(fg[i], fin_sys["FinMA-7B (official prompt)"][i]) - wf1(fg[i], fin_sys["Ours, 3-seed ensemble"][i]))
                  - (wf1(g[j], finma[j]) - wf1(g[j], ours[j])))
    lo, hi = np.quantile(sh, [0.025, 0.975])
    p, x, y = mcnemar(g, finma, ours)
    if shrink >= MIN_SHRINK and lo > 0:
        verdict = "memorisation CONSISTENT (preliminary: AI labels)" if ai_gold else "memorisation CONSISTENT"
    elif lead_fresh >= MIN_SHRINK and p < 0.05:
        verdict = "memorisation NOT supported"
    else:
        verdict = "INCONCLUSIVE"
    lines += ["", "## 2. The decision (rule fixed before the fresh results existed)", "",
              f"- FinMA's lead over our ensemble on the FinBen test: **{lead_fin:+.4f}**",
              f"- FinMA's lead on the fresh sentences: **{lead_fresh:+.4f}** (McNemar p = {p:.2g}; only FinMA right {x}, only ours right {y})",
              f"- Shrink: **{shrink:+.4f}**, 95% CI [{lo:+.3f}, {hi:+.3f}]", "",
              f"**Verdict: {verdict}.**", "",
              *(["*Missing check: no human has labelled or spot-checked these sentences; the gold labels are an AI's "
                 "(see section 4). Treat the verdict as preliminary until `c2_label.py --spotcheck 40` is done.*", ""]
                if ai_gold and not (FRESH / "spotcheck.csv").exists() else []),
              f"*Rule: supported if the lead shrinks by ≥ {MIN_SHRINK} with a CI excluding 0; not supported if FinMA still leads by "
              f"≥ {MIN_SHRINK} with p < 0.05; otherwise inconclusive.*", ""]

    # breakdowns + sensitivity
    sel_col = cand.get("selection", pd.Series(["random"] * len(cand))).values[keep]
    lines += ["## 3. Breakdowns", "", "| System | wF1, random sample | wF1, negative-keyword enrichment | Negative-class F1 |", "|---|---|---|---|"]
    for k, pr in systems.items():
        r = sel_col == "random"
        lines.append(f"| {k} | {wf1(g[r], pr[r]):.4f} (n={r.sum()}) | {wf1(g[~r], pr[~r]):.4f} (n={(~r).sum()}) | "
                     f"{f1_score(g, pr, labels=['negative'], average='macro', zero_division=0):.4f} |")
    cl_file = FRESH / "labels_claude.csv"
    sc_file = FRESH / "spotcheck.csv"
    if ai_gold:   # gold IS the Claude pass, so comparing the two would be 100% by construction
        lines += ["", "## 4. Label reliability", ""]
        sc = pd.read_csv(sc_file, keep_default_na=False, dtype=str) if sc_file.exists() else None
        sc = sc[sc.label != ""] if sc is not None else None
        if sc is not None and len(sc):
            gold_sc = lab.set_index("id").loc[sc.id, "human"].values
            lines.append(f"Human spot-check: your blind labels on {len(sc)} random sentences agree with the AI answer key "
                         f"**{np.mean(sc.label.values == gold_sc):.1%}** of the time (Cohen's kappa "
                         f"{cohen_kappa_score(sc.label.values, gold_sc):.3f}).")
        else:
            lines.append("No human check of the AI answer key yet. Run `c2_label.py --spotcheck 40` (~8 min) to measure it.")
        lines.append("")
    elif cl_file.exists():
        cl = pd.read_csv(cl_file, keep_default_na=False, dtype=str).set_index("id").loc[lab.id, "label"].values
        both = keep & np.isin(cl, LABELS) & (lab.human.values != "")
        human = lab.human.values
        lines += ["", "## 4. Label reliability and sensitivity", "",
                  f"Your blind labels vs the independent second annotator (Claude), {both.sum()} sentences: agreement "
                  f"{np.mean(human[both] == cl[both]):.1%}, Cohen's kappa {cohen_kappa_score(human[both], cl[both]):.3f}.", "",
                  "| System | wF1 vs YOUR labels | wF1 vs second annotator's labels |", "|---|---|---|"]
        cl_keep = np.isin(cl, LABELS)
        for k in systems:
            full_pred = {"E4B-it zero-shot": preds.get("e4b_zeroshot"), "FinMA-7B (official prompt)": preds["finma_7b"]}.get(k)
            if k == "Ours, 3-seed ensemble":
                fp = ensemble([preds[n] for n in final])
            elif k.startswith("Ours, seed"):
                fp = preds[final[config.SEEDS.index(int(k.split()[-1]))]].pred.values
            else:
                fp = full_pred.pred.values
            lines.append(f"| {k} | {wf1(g, systems[k]):.4f} | {wf1(cl[cl_keep], fp[cl_keep]):.4f} |")
        lines += ["", "*If the verdict flips between the two label sets, the result depends on annotation choices, not models.*", ""]

C_DIR.mkdir(parents=True, exist_ok=True)
(C_DIR / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")
print("\n".join(lines))
